#ifndef DESC_H
#define DESC_H

#include <QMap>

extern "C" {
#include <linux/input.h>
}

const QMap<int, QString> KEY_DESC = {
  std::map<int, QString>::value_type(KEY_LEFTALT,"AL"),
  std::map<int, QString>::value_type(KEY_RIGHTALT,"AL"),
  std::map<int, QString>::value_type(KEY_BACKSPACE,"BS"),
  std::map<int, QString>::value_type(KEY_RIGHTBRACE,"CB"),
  std::map<int, QString>::value_type(KEY_CAPSLOCK,"CL"),
  std::map<int, QString>::value_type(KEY_RIGHTCTRL,"CT"),
  std::map<int, QString>::value_type(KEY_LEFTCTRL,"CT"),

  std::map<int, QString>::value_type(KEY_DELETE,"DE"),
  std::map<int, QString>::value_type(KEY_DOWN,"DN"),
  std::map<int, QString>::value_type(KEY_END,"ED"),
  std::map<int, QString>::value_type(KEY_ESC,"ES"),
  std::map<int, QString>::value_type(KEY_ENTER,"ET"),
  std::map<int, QString>::value_type(KEY_F1,"FA"),
  std::map<int, QString>::value_type(KEY_F2,"FB"),
  std::map<int, QString>::value_type(KEY_F3,"FC"),
  std::map<int, QString>::value_type(KEY_F4,"FD"),
  std::map<int, QString>::value_type(KEY_F5,"FE"),
  std::map<int, QString>::value_type(KEY_F6,"FF"),
  std::map<int, QString>::value_type(KEY_F7,"FG"),
  std::map<int, QString>::value_type(KEY_F8,"FH"),
  std::map<int, QString>::value_type(KEY_F9,"FI"),
  std::map<int, QString>::value_type(KEY_F10,"FJ"),
  std::map<int, QString>::value_type(KEY_F11,"FK"),
  std::map<int, QString>::value_type(KEY_F12,"FL"),
  std::map<int, QString>::value_type(KEY_DOT,"GT"),
  std::map<int, QString>::value_type(KEY_HOME,"HO"),
  std::map<int, QString>::value_type(KEY_INSERT,"IS"),
  std::map<int, QString>::value_type(KEY_A,"KA"),
  std::map<int, QString>::value_type(KEY_B,"KB"),
  std::map<int, QString>::value_type(KEY_C,"KC"),
  std::map<int, QString>::value_type(KEY_D,"KD"),
  std::map<int, QString>::value_type(KEY_E,"KE"),
  std::map<int, QString>::value_type(KEY_F,"KF"),
  std::map<int, QString>::value_type(KEY_G,"KG"),
  std::map<int, QString>::value_type(KEY_H,"KH"),
  std::map<int, QString>::value_type(KEY_I,"KI"),
  std::map<int, QString>::value_type(KEY_J,"KJ"),
  std::map<int, QString>::value_type(KEY_K,"KK"),
  std::map<int, QString>::value_type(KEY_L,"KL"),
  std::map<int, QString>::value_type(KEY_M,"KM"),
  std::map<int, QString>::value_type(KEY_N,"KN"),
  std::map<int, QString>::value_type(KEY_O,"KO"),
  std::map<int, QString>::value_type(KEY_P,"KP"),
  std::map<int, QString>::value_type(KEY_Q,"KQ"),
  std::map<int, QString>::value_type(KEY_R,"KR"),
  std::map<int, QString>::value_type(KEY_S,"KS"),
  std::map<int, QString>::value_type(KEY_T,"KT"),
  std::map<int, QString>::value_type(KEY_U,"KU"),
  std::map<int, QString>::value_type(KEY_V,"KV"),
  std::map<int, QString>::value_type(KEY_W,"KW"),
  std::map<int, QString>::value_type(KEY_X,"KX"),
  std::map<int, QString>::value_type(KEY_Y,"KY"),
  std::map<int, QString>::value_type(KEY_Z,"KZ"),
  std::map<int, QString>::value_type(KEY_LEFT,"LF"),
  std::map<int, QString>::value_type(KEY_COMMA,"LT"),
  std::map<int, QString>::value_type(KEY_MINUS,"MI"),
  std::map<int, QString>::value_type(KEY_1,"NA"),
  std::map<int, QString>::value_type(KEY_2,"NB"),
  std::map<int, QString>::value_type(KEY_3,"NC"),
  std::map<int, QString>::value_type(KEY_4,"ND"),
  std::map<int, QString>::value_type(KEY_5,"NE"),
  std::map<int, QString>::value_type(KEY_6,"NF"),
  std::map<int, QString>::value_type(KEY_7,"NG"),
  std::map<int, QString>::value_type(KEY_8,"NH"),
  std::map<int, QString>::value_type(KEY_9,"NI"),
  std::map<int, QString>::value_type(KEY_0,"NJ"),
  std::map<int, QString>::value_type(KEY_LEFTBRACE,"OB"),
  std::map<int, QString>::value_type(KEY_PAGEDOWN,"PD"),
  std::map<int, QString>::value_type(KEY_BACKSLASH,"PI"),
  std::map<int, QString>::value_type(KEY_EQUAL,"PL"),
  std::map<int, QString>::value_type(KEY_SYSRQ,"PS"), // PRINTSCREEN
  std::map<int, QString>::value_type(KEY_PAGEUP,"PU"),
  std::map<int, QString>::value_type(KEY_SLASH,"QS"),
  std::map<int, QString>::value_type(KEY_APOSTROPHE,"QU"), // 撇号
  std::map<int, QString>::value_type(KEY_RIGHT,"RI"),
  std::map<int, QString>::value_type(KEY_SEMICOLON,"SE"),
  std::map<int, QString>::value_type(KEY_LEFTSHIFT,"SH"),
  std::map<int, QString>::value_type(KEY_RIGHTSHIFT,"SH"),
  std::map<int, QString>::value_type(KEY_SPACE,"SP"),
  std::map<int, QString>::value_type(KEY_TAB,"TA"),
  std::map<int, QString>::value_type(KEY_GRAVE,"TI"),
  std::map<int, QString>::value_type(KEY_UP,"UP"),
  std::map<int, QString>::value_type(KEY_LEFTMETA,"WI"),
};

#endif // DESC_H
